## config cluster schema ##
clusters:
  - name: "cluster name"
    api_ip: "..."
    ingress_ip: "..."
    external_port: "<auto / device name>"
    network_api_port: "<auto / device name>"
    masters:
    - name: "A"
      type: "<vm / physical / bf>"
      node: ""
      ip: ""
    workers:
    - name: "A"
      type: "<vm / physical / bf>"
      ip: ""
      node: ""
      bmc_ip: "optional if bmc ip address is host ip + 1"
      bmc_user: "required if physical or bf"
      bmc_password: "required if physical or bf"
      disk_size: "in GB - default = 48 GB"
      sparse: "False or True"
    # optionally describe additional node attributes
    hosts:
    - name: "A"
      images_path: "/path/to/pool/directory"
      network_api_port: "<auto> to keep cluster default - <device name> to overwrite cluster default>"
