## config cluster schema ##
clusters:
  - name: "cluster name"
    api_vip: "..."
    ingress_vip: "..."
    external_port: "<auto / device name>"
    network_api_port: "<auto / device name>"
    ip_range: "IP range (<start>-<end>) to use for connectivity between cluster nodes (optional)"
    ip_mask: "IP mask (x.y.z.t) to use for connectivity between cluster nodes (optional)"
    masters:
    - name: "A"
      kind: "<vm / physical / bf>"
      node: ""
      ip: ""
      ram: "in MB - default = 32768 MB"
      cpu: "number of vcpus if this is a VM - default = 8"
    workers:
    - name: "A"
      kind: "<vm / physical / bf>"
      ip: ""
      node: ""
      bmc: "required if physical or bf. Can be an ip or hostname"
      bmc_user: "required if physical or bf"
      bmc_password: "required if physical or bf"
      disk_size: "in GB - default = 48 GB"
      sparse: "False or True"
      ram: "in MB - default = 32768 GB"
      cpu: "number of vcpus if this is a VM - default = 8"
    # optionally describe additional node attributes
    hosts:
    - name: "A"
      image_path: "/path/to/pool/directory"
      network_api_port: "<auto> to keep cluster default - <device name> to overwrite cluster default>"
      username: "<core> to connect to bms hosting vms"
      password: "password"
      pre_installed: "whether bm hosting vms is pre-installed in case of remote vm. Default: True"
